const fs = require("fs");
const path = require("path");

const filePath = path.join(__dirname, "src", "components", "Auth.jsx");
const lines = [];

lines.push(`import { useEffect, useMemo, useState, useRef } from 'react';`);
lines.push(`import {`);
lines.push(`  getAuth, onAuthStateChanged, GoogleAuthProvider,`);
lines.push(`  signInWithRedirect, getRedirectResult, signOut,`);
lines.push(`  sendEmailVerification, createUserWithEmailAndPassword,`);
lines.push(`  signInWithEmailAndPassword, updateProfile,`);
lines.push(`} from 'firebase/auth';`);
lines.push(`import { firebaseApp } from '../utils/firebaseConfig';`);
lines.push(`import { ensureUserProfile } from '../utils/profileManager';`);
lines.push(`import { setTheme, getThemeByCategory } from '../utils/themeManager';`);
lines.push(``);
lines.push(`const SESSION_KEY = 'scouts_user_session';`);
lines.push(``);
lines.push(`function getSession() {`);
lines.push(`  try { return JSON.parse(sessionStorage.getItem(SESSION_KEY)); }`);
lines.push(`  catch { return null; }`);
lines.push(`}`);
lines.push(`function saveSession(user) {`);
lines.push(`  sessionStorage.setItem(SESSION_KEY, JSON.stringify({ ...user, loginTime: Date.now() }));`);
lines.push(`}`);
lines.push(`function clearSession() {`);
lines.push(`  sessionStorage.removeItem(SESSION_KEY);`);
lines.push(`}`);
lines.push(``);
lines.push(`export default function Auth() {`);
lines.push(`  const auth = useMemo(() => getAuth(firebaseApp), []);`);
lines.push(`  const googleProvider = useMemo(() => new GoogleAuthProvider(), []);`);
lines.push(`  const sessionLocked = useRef(false);`);
lines.push(`  const [loading, setLoading] = useState(true);`);
lines.push(`  const [message, setMessage] = useState('');`);
lines.push(`  const [user, setUser] = useState(getSession());`);
lines.push(`  const [tab, setTab] = useState('login');`);
lines.push(`  const [loginEmail, setLoginEmail] = useState('');`);
lines.push(`  const [loginPassword, setLoginPassword] = useState('');`);
lines.push(`  const [signupName, setSignupName] = useState('');`);
lines.push(`  const [signupEmail, setSignupEmail] = useState('');`);
lines.push(`  const [signupPassword, setSignupPassword] = useState('');`);
lines.push(`  const [signupConfirm, setSignupConfirm] = useState('');`);
lines.push(``);
lines.push(`  function applyAuthenticatedUser(fbUser) {`);
lines.push(`    if (!fbUser) {`);
lines.push(`      if (sessionLocked.current) {`);
lines.push(`        console.log('Session locked - ignoring onAuthStateChanged(null)');`);
lines.push(`        setLoading(false);`);
lines.push(`        return null;`);
lines.push(`      }`);
lines.push(`      setUser(null); clearSession(); setLoading(false); return null;`);
lines.push(`    }`);
lines.push(`    const profile = ensureUserProfile(fbUser);`);
lines.push(`    const u = { id: profile.uid, name: profile.name, email: profile.email, avatar: profile.avatar, category: profile.category ?? null, emailVerified: profile.emailVerified };`);
lines.push(`    setUser(u); saveSession(u);`);
lines.push(`    if (profile.category) { setTheme(getThemeByCategory(profile.category)); }`);
lines.push(`    setLoading(false);`);
lines.push(`    sessionLocked.current = false;`);
lines.push(`    return u;`);
lines.push(`  }`);
lines.push(``);
lines.push(`  useEffect(() => {`);
lines.push(`    const unsub = onAuthStateChanged(auth, (fbUser) => { applyAuthenticatedUser(fbUser); });`);
lines.push(`    return () => unsub();`);
lines.push(`  }, [auth]);`);
lines.push(``);
lines.push(`  useEffect(() => {`);
lines.push(`    let active = true;`);
lines.push(`    async function handleRedirectResult() {`);
lines.push(`      try {`);
lines.push(`        const result = await getRedirectResult(auth);`);
lines.push(`        if (!active) return;`);
lines.push(`        if (result?.user) { sessionLocked.current = true; applyAuthenticatedUser(result.user); setMessage('Signed in successfully'); }`);
lines.push(`      } catch (err) {`);
lines.push(`        if (active) { setMessage('Google sign-in could not be completed.'); setLoading(false); }`);
lines.push(`      }`);
lines.push(`    }`);
lines.push(`    handleRedirectResult();`);
lines.push(`    return () => { active = false; };`);
lines.push(`  }, [auth]);`);
lines.push(``);
lines.push(`  async function handleGoogleSignIn() {`);
lines.push(`    setMessage(''); setLoading(true);`);
lines.push(`    try { setMessage('Redirecting to Google...'); await signInWithRedirect(auth, googleProvider); }`);
lines.push(`    catch (err) { setMessage('Google sign-in could not be started.'); setLoading(false); }`);
lines.push(`  }`);
lines.push(``);
lines.push(`  async function handleEmailSignIn(e) {`);
lines.push(`    e?.preventDefault?.(); setMessage(''); setLoading(true);`);
lines.push(`    try {`);
lines.push(`      sessionLocked.current = true;`);
lines.push(`      const cred = await signInWithEmailAndPassword(auth, loginEmail, loginPassword);`);
lines.push(`      if (!cred.user) { setMessage('Sign-in succeeded but no user object.'); setLoading(false); sessionLocked.current = false; return; }`);
lines.push(`      const profile = ensureUserProfile(cred.user);`);
lines.push(`      const u = { id: profile.uid, name: profile.name, email: profile.email, avatar: profile.avatar, category: profile.category || 'scout', emailVerified: profile.emailVerified };`);
lines.push(`      setUser(u); saveSession(u);`);
lines.push(`      if (u.category) { setTheme(getThemeByCategory(u.category)); }`);
lines.push(`      setMessage('Signed in successfully');`);
lines.push(`      setTimeout(() => { window.location.hash = '#/'; }, 300);`);
lines.push(`    } catch (err) {`);
lines.push(`      sessionLocked.current = false;`);
lines.push(`      const c = err?.code || '';`);
lines.push(`      let m = err?.message || 'Email sign-in failed';`);
lines.push(`      if (c === 'auth/user-not-found') m = 'No account found with this email.';`);
lines.push(`      else if (c === 'auth/wrong-password' || c === 'auth/invalid-credential') m = 'Invalid email or password.';`);
lines.push(`      else if (c === 'auth/too-many-requests') m = 'Too many attempts. Please try again later.';`);
lines.push(`      setMessage(m);`);
lines.push(`    } finally { setLoading(false); }`);
lines.push(`  }`);
lines.push(``);
lines.push(`  async function handleEmailSignUp(e) {`);
lines.push(`    e?.preventDefault?.(); setMessage('');`);
lines.push(`    if (!signupName || !signupEmail || !signupPassword) { setMessage('Please fill all fields'); return; }`);
lines.push(`    if (signupPassword !== signupConfirm) { setMessage('Passwords do not match'); return; }`);
lines.push(`    setLoading(true);`);
lines.push(`    try {`);
lines.push(`      sessionLocked.current = true;`);
lines.push(`      const cred = await createUserWithEmailAndPassword(auth, signupEmail, signupPassword);`);
lines.push(`      if (signupName) { try { await updateProfile(cred.user, { displayName: signupName }); } catch (e) { console.error(e); } }`);
lines.push(`      try { await sendEmailVerification(cred.user); } catch (e) { console.warn('Verification email not sent', e?.code); }`);
lines.push(`      const profile = ensureUserProfile(cred.user);`);
lines.push(`      const u = { id: profile.uid, name: profile.name, email: profile.email, avatar: profile.avatar, category: profile.category || 'scout', emailVerified: profile.emailVerified };`);
lines.push(`      setUser(u); saveSession(u);`);
lines.push(`      if (u.category) { setTheme(getThemeByCategory(u.category)); }`);
lines.push(`      setMessage('Account created! Redirecting...');`);
lines.push(`      setTimeout(() => { window.location.hash = '#/'; }, 800);`);
lines.push(`    } catch (err) {`);
lines.push(`      sessionLocked.current = false;`);
lines.push(`      const c = err?.code || '';`);
lines.push(`      let m = err?.message || 'Sign-up failed';`);
lines.push(`      if (c === 'auth/email-already-in-use') m = 'This email is already registered. Please log in instead.';`);
lines.push(`      else if (c === 'auth/weak-password') m = 'Password is too weak. Use at least 6 characters.';`);
lines.push(`      else if (c === 'auth/operation-not-allowed') m = 'Email/password sign-up is not enabled. Enable it in Firebase Console > Authentication > Sign-in method.';`);
lines.push(`      setMessage(m);`);
lines.push(`    } finally { setLoading(false); }`);
lines.push(`  }`);
lines.push(``);
lines.push(`  async function handleSignOut() {`);
lines.push(`    setMessage(''); setLoading(true);`);
lines.push(`    try { sessionLocked.current = false; await signOut(auth); clearSession(); setUser(null); setMessage('Signed out'); }`);
lines.push(`    finally { setLoading(false); }`);
lines.push(`  }`);
lines.push(``);
lines.push(`  if (loading) {`);
lines.push(`    return (<div className="min-h-screen bg-gradient-to-br from-[#14532d] via-[#16a34a] to-[#84cc16] flex items-center justify-center p-4"><div className="text-emerald-50">Loading...</div>);`);
lines.push(`  }`);
lines.push(`  if (user && user.category) {`);
lines.push(`    return (`);
lines.push(`      <div className="min-h-screen bg-gradient-to-br from-[#14532d] via-[#16a34a] to-[#84cc16] flex items-center justify-center p-4">`);
lines.push(`        <div className="w-full max-w-md bg-emerald-950/90 border border-white/10 rounded-3xl shadow-2xl p-8 text-center text-white">`);
lines.push(`          <h2 className="text-2xl font-bold text-white mb-2">You&apos;re signed in</h2>`);
lines.push(`          <p className="text-emerald-200 mb-4">{user.name} &mdash; {user.email}</p>`);
lines.push(`          <p className="text-emerald-200 mb-6">Category: <strong className="text-emerald-300">{user.category}</strong></p>`);
lines.push(`          <div className="flex gap-4 justify-center">`);
lines.push(`            <button onClick={() => { window.location.hash = '#/'; }} className="py-2 px-4 bg-emerald-600 rounded text-white hover:bg-emerald-700">Go to home</button>`);
lines.push(`            <button onClick={handleSignOut} className="py-2 px-4 bg-emerald-500 rounded text-white hover:bg-emerald-600">Sign out</button>`);
lines.push(`          </div>`);
lines.push(`          {!user.emailVerified && <div className="mt-4 text-sm text-emerald-200">Check your email to verify your account.</div>}`);
lines.push(`        </div>`);
lines.push(`      </div>`);
lines.push(`    );`);
lines.push(`  }`);
lines.push(`  return (`);
lines.push(`    <div className="min-h-screen bg-gradient-to-br from-[#14532d] via-[#16a34a] to-[#84cc16] flex items-center justify-center p-4">`);
lines.push(`      <div className="w-full max-w-5xl grid md:grid-cols-2 gap-6">`);
lines.push(`        <div className="bg-emerald-950/90 border border-white/10 rounded-3xl shadow-2xl p-8 flex flex-col justify-center text-white">`);
lines.push(`          <div className="text-center">`);
lines.push(`            <div className="inline-flex items-center justify-center w-20 h-20 bg-emerald-600 rounded-full mb-6 shadow-lg shadow-emerald-500/30 text-4xl">&#9876;</div>`);
lines.push(`            <h1 className="text-3xl font-bold">Amynabad Scouts</h1>`);
lines.push(`            <p className="text-emerald-200 mt-4 text-base leading-7 max-w-xl mx-auto">&ldquo;Try and leave this world a little better than you found it.&rdquo;</p>`);
lines.push(`            <p className="text-emerald-300 mt-4 text-sm uppercase tracking-[0.3em] text-opacity-90">&mdash; Robert Baden-Powell</p>`);
lines.push(`          </div>`);
lines.push(`        </div>`);
lines.push(`        <div className="bg-emerald-950/90 border border-white/10 rounded-3xl shadow-2xl p-8 text-white">`);
lines.push(`          <button type="button" onClick={handleGoogleSignIn} disabled={loading} className="w-full py-3 px-4 rounded-lg bg-emerald-600 hover:bg-emerald-700 text-white font-semibold transition mb-4">Sign in with Google</button>`);
lines.push(`          <div className="flex gap-2 mb-6">`);
lines.push(`            <button type="button" onClick={() => setTab('login')} className={'flex-1 py-2 rounded ' + (tab === 'login' ? 'bg-emerald-600 text-white' : 'bg-emerald-900 text-emerald-200')}>Login</button>`);
lines.push(`            <button type="button" onClick={() => setTab('signup')} className={'flex-1 py-2 rounded ' + (tab === 'signup' ? 'bg-emerald-600 text-white' : 'bg-emerald-900 text-emerald-200')}>Sign Up</button>`);
lines.push(`          </div>`);
lines.push(`          {tab === 'login' ? (`);
lines.push(`            <form onSubmit={handleEmailSignIn} className="space-y-4">`);
lines.push(`              <div><label className="block text-emerald-200 text-sm mb-1">Email</label><input type="email" value={loginEmail} onChange={e => setLoginEmail(e.target.value)} className="w-full px-3 py-2 rounded bg-emerald-900 text-white" /></div>`);
lines.push(`              <div><label className="block text-emerald-200 text-sm mb-1">Password</label><input type="password" value={loginPassword} onChange={e => setLoginPassword(e.target.value)} className="w-full px-3 py-2 rounded bg-emerald-900 text-white" /></div>`);
lines.push(`              <div className="flex gap-2">`);
lines.push(`                <button type="submit" disabled={loading} className="flex-1 py-2 bg-emerald-600 rounded text-white hover:bg-emerald-700">{loading ? 'Signing in...' : 'Sign in'}</button>`);
lines.push(`                <button type="button" onClick={() => { setLoginEmail(''); setLoginPassword(''); setMessage(''); }} className="py-2 px-3 bg-emerald-900 rounded text-emerald-200">Clear</button>`);
lines.push(`              </div>`);
lines.push(`            </form>`);
lines.push(`          ) : (`);
lines.push(`            <form onSubmit={handleEmailSignUp} className="space-y-4">`);
lines.push(`              <div><label className="block text-emerald-200 text-sm mb-1">Full name</label><input type="text" value={signupName} onChange={e => setSignupName(e.target.value)} className="w-full px-3 py-2 rounded bg-emerald-900 text-white" /></div>`);
lines.push(`              <div><label className="block text-emerald-200 text-sm mb-1">Email</label><input type="email" value={signupEmail} onChange={e => setSignupEmail(e.target.value)} className="w-full px-3 py-2 rounded bg-emerald-900 text-white" /></div>`);
lines.push(`              <div><label className="block text-emerald-200 text-sm mb-1">Password</label><input type="password" value={signupPassword} onChange={e => setSignupPassword(e.target.value)} className="w-full px-3 py-2 rounded bg-emerald-900 text-white" /></div>`);
lines.push(`              <div><label className="block text-emerald-200 text-sm mb-1">Confirm password</label><input type="password" value={signupConfirm} onChange={e => setSignupConfirm(e.target.value)} className="w-full px-3 py-2 rounded bg-emerald-900 text-white" /></div>`);
lines.push(`              <div className="flex gap-2">`);
lines.push(`                <button type="submit" disabled={loading} className="flex-1 py-2 bg-emerald-600 rounded text-white hover:bg-emerald-700">{loading ? 'Creating...' : 'Create account'}</button>`);
lines.push(`                <button type="button" onClick={() => { setSignupName(''); setSignupEmail(''); setSignupPassword(''); setSignupConfirm(''); setMessage(''); }} className="py-2 px-3 bg-emerald-900 rounded text-emerald-200">Clear</button>`);
lines.push(`              </div>`);
lines.push(`            </form>`);
lines.push(`          )}`);
lines.push(`          {message && <div className="mt-4 text-sm text-emerald-200">{message}</div>}`);
lines.push(`        </div>`);
lines.push(`      </div>`);
lines.push(`    </div>`);
lines.push(`  );`);
lines.push(`}`);

const content = lines.join("\n");
const openCount = (content.match(/<div\b[^>]*>/g) || []).length;
const closeCount = (content.match(/<\/div>/g) || []).length;

fs.writeFileSync(filePath, content, "utf8");
console.log("Auth.jsx written successfully");
console.log(`Divs: ${openCount} open, ${closeCount} close - balanced: ${openCount === closeCount}`);
